### ISSUE TITLE
Non DT fan palm tree in minecraft:desert

### ISSUE THREAD

**Issue by Elnhomantia** [joe-vettek/Dynamic-Trees-for-Blooming-Nature#1]
![image](https://github.com/joe-vettek/Dynamic-Trees-for-Blooming-Nature/assets/87205079/ee828784-b939-4a70-a512-04aaeadab331)

As you can see, "basic" fan palm tree can still spawn in desert

**Comment by joe-vettek** [comment]
what's in your slot.

**Comment by Nyfaria** [comment]
Hi, that is an Oasis structure.
DT does not replace Trees in structures as they are not actual trees.

**Comment by joe-vettek** [comment]
would fix it in sometime

**Comment by Elnhomantia** [comment]
Yeah sorry for what was in my slots, it was because I wasn't sure "fan" was part of the tree name, so I verified with the sappling and the seed. And yes it seems it's an oasis, there is moss and water of the floor

**Comment by joe-vettek** [comment]
upload a new version to curseforge to remove the tree, instead it with a sapling. And maybe the fan palm leaves model needs more work. There are some problems.
