### ISSUE TITLE
Blooming Nature Trees Not Spawning

### ISSUE THREAD

**Issue by Maddi004** [joe-vettek/Dynamic-Trees-for-Blooming-Nature#2]
Larch trees and aspens are not spawning in their respective biomes. They can be planted and grown via seeds, and they function normally. They just dont spawn in with world generation.
![2024-11-20_22 18 26](https://github.com/user-attachments/assets/048b728f-b46d-46cc-b3d6-eab2549f6d29)
![2024-11-20_22 18 33](https://github.com/user-attachments/assets/d6ead00b-4c04-4ef4-9ae0-20a7d492b1ed)
![2024-11-20_22 19 54](https://github.com/user-attachments/assets/5b1af4bf-4897-401f-be6b-a38786c6c727)
![2024-11-20_22 20 01](https://github.com/user-attachments/assets/b20e3240-af82-4130-b649-4f06484cdf83)
Here are pictures of the biomes with no blooming nature trees.

**Comment by joe-vettek** [comment]
![image](https://github.com/user-attachments/assets/e587e2cd-8ef7-46d7-8b22-273301c516ee)
it seems work. maybe some of your dt addons broken it

**Comment by Maddi004** [comment]
That is so strange. The mod pack I took the screenshots from only had dt, dt blooming nature, blooming nature, let's do api and architechtury api installed on it.

**Comment by joe-vettek** [comment]
I once made up a modpack with dt for let‘s’ do which i can find trees normally.
I don't know if it has anything to do with the forge version.

**Comment by Maddi004** [comment]
Maybe. The version of forge I used for the pack I tested with is 47.3.12. I also noticed that I can find the dt fan palm trees spawning normally. I think its just a specific problem with the dt aspens and larch trees. Maybe its something to do the the way Let's Do itself implements tree spawning? But my knowledge on modding is super limited so honestly I have no idea.

**Comment by joe-vettek** [comment]
I know what the problem is, something has changed in the world generation of Dynamic Trees, this will take some time to confirm.

**Comment by Maddi004** [comment]
Ok sounds good. Thank you so much for the help!

**Comment by joe-vettek** [comment]
wait dynamic trees upgrades. the problem is not with here.
